# Generated by Django 4.0.2 on 2022-02-18 21:23

from django.db import migrations, models
import meraki.custom_storages


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=meraki.custom_storages.ImageStorage(), upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=meraki.custom_storages.ImageStorage(), upload_to='thumbnails/'),
        ),
    ]
